[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
workflow_engine = "ETggxWEvQkEu3EPh5APnpY9C5oDMnNDStYtsgaaCW3BB"

[programs.devnet]
workflow_engine = "ETggxWEvQkEu3EPh5APnpY9C5oDMnNDStYtsgaaCW3BB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
